/* mdcm_cfg: Data Cache/Memory Configuration Register */
#define MDCM_CFG_DEST_OFFSET		0
#define MDCM_CFG_DWAY_OFFSET		3
#define MDCM_CFG_DSZ_OFFSET		6
#define MDCM_CFG_DLCK_OFFSET		9
#define MDCM_CFG_DC_ECC_OFFSET		10
#define MDCM_CFG_DLMB_OFFSET		12
#define MDCM_CFG_DLMSZ_OFFSET		15
#define MDCM_CFG_ULM_2BANK_OFFSET	20
#define MDCM_CFG_DLM_ECC_OFFSET		21


#define MDCM_CFG_DEST_MASK	(0x7  << MDCM_CFG_DEST_OFFSET)
#define MDCM_CFG_DWAY_MASK	(0x7  << MDCM_CFG_DWAY_OFFSET)
#define MDCM_CFG_DSZ_MASK	(0x7  << MDCM_CFG_DSZ_OFFSET)
#define MDCM_CFG_DLCK_MASK	(0x1  << MDCM_CFG_DLCK_OFFSET)
#define MDCM_CFG_DC_ECC_MASK	(0x3  << MDCM_CFG_DC_ECC_OFFSET)
#define MDCM_CFG_DLMB_MASK	(0x7  << MDCM_CFG_DLMB_OFFSET)
#define MDCM_CFG_DLMSZ_MASK	(0x1f << MDCM_CFG_DLMSZ_OFFSET)
#define MDCM_CFG_ULM_2BANK_MASK	(0x1  << MDCM_CFG_ULM_2BANK_OFFSET)
#define MDCM_CFG_DLM_ECC_MASK	(0x3  << MDCM_CFG_DLM_ECC_OFFSET)


/* ucctlcommand */
/* D-cache operation */
#define CCTL_L1D_VA_INVAL	0
#define CCTL_L1D_VA_WB		1
#define CCTL_L1D_VA_WBINVAL	2
